[package]
name = "chinese-tokenizer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
js-sys = "0.3.60"
once_cell = "1.16.0"
rustc-hash = "1.1.0"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = ['-O4', '-g']
