name: CI

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Deno
      uses: denoland/setup-deno@v1.1.1
      with:
        deno-version: 1.x
    - name: Setup Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
    - name: Setup wasm-pack
      uses: jetli/wasm-pack-action@v0.4.0
    - name: Run tests
      run: deno task test
    - name: Build
      run: deno task build-dev
